# Generated by Django 3.2.6 on 2022-02-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crunchapp', '0002_userprofile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recurring_billing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
