# Generated by Django 3.2.6 on 2022-02-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crunchapp', '0003_userprofile_recurring_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_refrence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
